// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_weight_bisquare
arma::vec rcpp_weight_bisquare(arma::vec x, double k);
RcppExport SEXP _VBRobM_rcpp_weight_bisquare(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_weight_bisquare(x, k));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_psi_bisquare
arma::vec rcpp_psi_bisquare(arma::vec x, double k);
RcppExport SEXP _VBRobM_rcpp_psi_bisquare(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_psi_bisquare(x, k));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_coord_descend
List rcpp_coord_descend(arma::vec beta0, arma::vec s0, arma::vec Yi, arma::mat Xi, arma::mat Ji, arma::vec vi, int n, double k1, double k2, double K2, double tol);
RcppExport SEXP _VBRobM_rcpp_coord_descend(SEXP beta0SEXP, SEXP s0SEXP, SEXP YiSEXP, SEXP XiSEXP, SEXP JiSEXP, SEXP viSEXP, SEXP nSEXP, SEXP k1SEXP, SEXP k2SEXP, SEXP K2SEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type s0(s0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yi(YiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xi(XiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ji(JiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vi(viSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type k1(k1SEXP);
    Rcpp::traits::input_parameter< double >::type k2(k2SEXP);
    Rcpp::traits::input_parameter< double >::type K2(K2SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_coord_descend(beta0, s0, Yi, Xi, Ji, vi, n, k1, k2, K2, tol));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_coord_descend_stg2
List rcpp_coord_descend_stg2(arma::vec beta0, arma::vec s0, arma::vec Yi, arma::mat Xi, arma::mat Ji, arma::vec vi, int n, double k1, double k2, double K1, double K2, double K3, double tol);
RcppExport SEXP _VBRobM_rcpp_coord_descend_stg2(SEXP beta0SEXP, SEXP s0SEXP, SEXP YiSEXP, SEXP XiSEXP, SEXP JiSEXP, SEXP viSEXP, SEXP nSEXP, SEXP k1SEXP, SEXP k2SEXP, SEXP K1SEXP, SEXP K2SEXP, SEXP K3SEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type s0(s0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Yi(YiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xi(XiSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Ji(JiSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vi(viSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type k1(k1SEXP);
    Rcpp::traits::input_parameter< double >::type k2(k2SEXP);
    Rcpp::traits::input_parameter< double >::type K1(K1SEXP);
    Rcpp::traits::input_parameter< double >::type K2(K2SEXP);
    Rcpp::traits::input_parameter< double >::type K3(K3SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_coord_descend_stg2(beta0, s0, Yi, Xi, Ji, vi, n, k1, k2, K1, K2, K3, tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_VBRobM_rcpp_weight_bisquare", (DL_FUNC) &_VBRobM_rcpp_weight_bisquare, 2},
    {"_VBRobM_rcpp_psi_bisquare", (DL_FUNC) &_VBRobM_rcpp_psi_bisquare, 2},
    {"_VBRobM_rcpp_coord_descend", (DL_FUNC) &_VBRobM_rcpp_coord_descend, 11},
    {"_VBRobM_rcpp_coord_descend_stg2", (DL_FUNC) &_VBRobM_rcpp_coord_descend_stg2, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_VBRobM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
