# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_weight_bisquare <- function(x, k) {
    .Call('_VBRobM_rcpp_weight_bisquare', PACKAGE = 'VBRobM', x, k)
}

rcpp_psi_bisquare <- function(x, k) {
    .Call('_VBRobM_rcpp_psi_bisquare', PACKAGE = 'VBRobM', x, k)
}

rcpp_coord_descend <- function(beta0, s0, Yi, Xi, Ji, vi, n, k1, k2, K2, tol) {
    .Call('_VBRobM_rcpp_coord_descend', PACKAGE = 'VBRobM', beta0, s0, Yi, Xi, Ji, vi, n, k1, k2, K2, tol)
}

rcpp_coord_descend_stg2 <- function(beta0, s0, Yi, Xi, Ji, vi, n, k1, k2, K1, K2, K3, tol) {
    .Call('_VBRobM_rcpp_coord_descend_stg2', PACKAGE = 'VBRobM', beta0, s0, Yi, Xi, Ji, vi, n, k1, k2, K1, K2, K3, tol)
}

